-- ==============================================================================
-- SCRIPT DE INICIALIZACIÓN PARA STAGING + DELIVERY V2
-- Ejecutar en: Supabase SQL Editor del proyecto staging
-- ==============================================================================

-- ====================
-- 1. ESQUEMA BASE
-- ====================

DROP TABLE IF EXISTS payment_webhook_event CASCADE;
DROP TABLE IF EXISTS payment_intent CASCADE;
DROP TABLE IF EXISTS detalle_devolucion CASCADE;
DROP TABLE IF EXISTS devolucion CASCADE;
DROP TABLE IF EXISTS historial CASCADE;
DROP TABLE IF EXISTS pedido_inventario_mov CASCADE;
DROP TABLE IF EXISTS reserva_stock_item CASCADE;
DROP TABLE IF EXISTS reserva_stock CASCADE;
DROP TABLE IF EXISTS detalle_pedido CASCADE;
DROP TABLE IF EXISTS boleta CASCADE;
DROP TABLE IF EXISTS factura CASCADE;
DROP TABLE IF EXISTS comprobante CASCADE;
DROP TABLE IF EXISTS entrega_evidencia CASCADE;
DROP TABLE IF EXISTS delivery_event CASCADE;
DROP TABLE IF EXISTS envio CASCADE;
DROP TABLE IF EXISTS pedido CASCADE;
DROP TABLE IF EXISTS salida_inventario CASCADE;
DROP TABLE IF EXISTS entrada_inventario CASCADE;
DROP TABLE IF EXISTS proveedor_producto CASCADE;
DROP TABLE IF EXISTS inventario CASCADE;
DROP TABLE IF EXISTS motorizado CASCADE;
DROP TABLE IF EXISTS delivery CASCADE;
DROP TABLE IF EXISTS almacen CASCADE;
DROP TABLE IF EXISTS proveedor CASCADE;
DROP TABLE IF EXISTS carrito CASCADE;
DROP TABLE IF EXISTS producto CASCADE;
DROP TABLE IF EXISTS marca CASCADE;
DROP TABLE IF EXISTS categoria CASCADE;
DROP TABLE IF EXISTS metodos_de_pago CASCADE;
DROP TABLE IF EXISTS reclamo CASCADE;
DROP TABLE IF EXISTS password_reset_token CASCADE;
DROP TABLE IF EXISTS email_verification_token CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;

CREATE TABLE usuario (
    id_usuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    contrasena VARCHAR(255) NOT NULL,
    fecha_registro TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    telefono VARCHAR(20),
    direccion_principal VARCHAR(255),
    rol VARCHAR(15) NOT NULL DEFAULT 'CLIENTE' CHECK (rol IN ('CLIENTE', 'ADMINISTRADOR', 'EMPLEADO', 'REPARTIDOR')),
    email_verificado BOOLEAN NOT NULL DEFAULT FALSE,
    email_verificado_en TIMESTAMPTZ NULL
);

CREATE TABLE email_verification_token (
    id_email_verification_token INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INT NOT NULL REFERENCES usuario(id_usuario),
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    used_at TIMESTAMPTZ NULL,
    CONSTRAINT uq_emailverificationtoken UNIQUE (token_hash)
);

CREATE TABLE password_reset_token (
    id_password_reset_token INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INT NOT NULL REFERENCES usuario(id_usuario),
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    used_at TIMESTAMPTZ NULL,
    CONSTRAINT uq_passwordresettoken UNIQUE (token_hash)
);

CREATE TABLE metodos_de_pago (
    id_metodo_pago INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_metodo VARCHAR(50) NOT NULL,
    detalles VARCHAR(255)
);

CREATE TABLE categoria (
    id_categoria INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_categoria VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE marca (
    id_marca INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_marca VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE proveedor (
    id_proveedor INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_proveedor VARCHAR(100) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    email VARCHAR(100),
    direccion VARCHAR(255)
);

CREATE TABLE almacen (
    id_almacen INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_almacen VARCHAR(100) NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    responsable VARCHAR(100) NOT NULL
);

CREATE TABLE delivery (
    id_delivery INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_empresa VARCHAR(100) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    email VARCHAR(100)
);

CREATE TABLE motorizado (
    id_motorizado INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    licencia VARCHAR(50) NOT NULL,
    id_delivery INT NOT NULL REFERENCES delivery(id_delivery),
    id_usuario INT NULL UNIQUE REFERENCES usuario(id_usuario)
);

CREATE TABLE producto (
    id_producto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_producto VARCHAR(100) NOT NULL,
    descripcion TEXT,
    precio DECIMAL(10,2) NOT NULL,
    imagen VARCHAR(255) NOT NULL DEFAULT '/assets/images/placeholder-product.png',
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    id_categoria INT NOT NULL REFERENCES categoria(id_categoria),
    id_marca INT NOT NULL REFERENCES marca(id_marca)
);

CREATE TABLE proveedor_producto (
    id_proveedor_producto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    precio_unitario DECIMAL(10,2) NOT NULL,
    precio_costo DECIMAL(10,2) NOT NULL,
    fecha_ultima_compra TIMESTAMPTZ,
    id_producto INT NOT NULL REFERENCES producto(id_producto),
    id_proveedor INT NOT NULL REFERENCES proveedor(id_proveedor)
);

CREATE TABLE inventario (
    id_inventario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad_disponible INT NOT NULL,
    fecha_ultima_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    id_producto INT NOT NULL REFERENCES producto(id_producto),
    id_almacen INT NOT NULL REFERENCES almacen(id_almacen)
);

CREATE TABLE entrada_inventario (
    id_entrada_inventario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad_recibida INT NOT NULL,
    fecha_entrada TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    motivo_entrada VARCHAR(255) NOT NULL,
    id_inventario INT NOT NULL REFERENCES inventario(id_inventario)
);

CREATE TABLE salida_inventario (
    id_salida_inventario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad_salida INT NOT NULL,
    fecha_salida TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    motivo_salida VARCHAR(255) NOT NULL,
    id_inventario INT NOT NULL REFERENCES inventario(id_inventario),
    id_usuario INT NULL REFERENCES usuario(id_usuario)
);

CREATE TABLE pedido (
    id_pedido INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    estado_pedido VARCHAR(50) NOT NULL
        CHECK (estado_pedido IN ('PENDIENTE_PAGO', 'PENDIENTE', 'PREPARADO', 'EN CAMINO', 'ENTREGADO', 'CANCELADO', 'REEMBOLSADO'))
        DEFAULT 'PENDIENTE_PAGO',
    total_pedido DECIMAL(10,2) NOT NULL,
    costo_envio DECIMAL(10,2),
    direccion_envio VARCHAR(255) NOT NULL,
    id_usuario INT NOT NULL REFERENCES usuario(id_usuario),
    id_metodo_pago INT NOT NULL REFERENCES metodos_de_pago(id_metodo_pago)
);

CREATE TABLE reserva_stock (
    id_reserva_stock INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INT NOT NULL REFERENCES pedido(id_pedido),
    id_usuario INT NOT NULL REFERENCES usuario(id_usuario),
    estado VARCHAR(20) NOT NULL CHECK (estado IN ('ACTIVA', 'CONSUMIDA', 'LIBERADA', 'EXPIRADA')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE reserva_stock_item (
    id_reserva_stock_item INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_reserva_stock INT NOT NULL REFERENCES reserva_stock(id_reserva_stock),
    id_producto INT NOT NULL REFERENCES producto(id_producto),
    cantidad INT NOT NULL CHECK (cantidad > 0),
    CONSTRAINT uq_reservastockitem UNIQUE (id_reserva_stock, id_producto)
);

CREATE TABLE pedido_inventario_mov (
    id_pedido_inventario_mov INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INT NOT NULL REFERENCES pedido(id_pedido),
    id_inventario INT NOT NULL REFERENCES inventario(id_inventario),
    tipo_mov VARCHAR(10) NOT NULL CHECK (tipo_mov IN ('SALIDA','ENTRADA')),
    cantidad INT NOT NULL CHECK (cantidad > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE envio (
    id_envio INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_rastreo VARCHAR(50) NOT NULL,
    transportista VARCHAR(100) NOT NULL,
    fecha_envio TIMESTAMPTZ,
    estado_envio VARCHAR(50) NOT NULL,
    costo_envio DECIMAL(10,2) NOT NULL,
    id_pedido INT NOT NULL REFERENCES pedido(id_pedido),
    id_delivery INT REFERENCES delivery(id_delivery),
    id_motorizado INT NULL REFERENCES motorizado(id_motorizado),
    asignado_por INT NULL REFERENCES usuario(id_usuario),
    fecha_asignacion TIMESTAMPTZ NULL,
    fecha_inicio_ruta TIMESTAMPTZ NULL,
    fecha_entrega TIMESTAMPTZ NULL,
    motivo_no_entrega TEXT NULL
);

CREATE TABLE delivery_event (
    id_delivery_event INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_envio INT NOT NULL REFERENCES envio(id_envio),
    id_pedido INT NOT NULL REFERENCES pedido(id_pedido),
    tipo_evento VARCHAR(50) NOT NULL,
    detalle TEXT NULL,
    payload_json TEXT NULL,
    id_usuario INT NULL REFERENCES usuario(id_usuario),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE entrega_evidencia (
    id_entrega_evidencia INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_envio INT NOT NULL REFERENCES envio(id_envio),
    id_pedido INT NOT NULL REFERENCES pedido(id_pedido),
    nombre_receptor VARCHAR(120) NOT NULL,
    dni_receptor VARCHAR(20) NULL,
    observacion TEXT NULL,
    foto_url VARCHAR(2048) NULL,
    lat DECIMAL(10,7) NULL,
    lng DECIMAL(10,7) NULL,
    id_usuario INT NULL REFERENCES usuario(id_usuario),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE comprobante (
    id_comprobante INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_comprobante VARCHAR(50) NOT NULL,
    numero_comprobante VARCHAR(50) NOT NULL UNIQUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    monto_total DECIMAL(10,2) NOT NULL,
    estado_comprobante VARCHAR(50) NOT NULL CHECK (estado_comprobante IN ('PENDIENTE','PAGADO','ANULADO','OBSERVADO')),
    fecha_emision TIMESTAMPTZ NULL,
    ultima_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    id_pedido INT NOT NULL REFERENCES pedido(id_pedido),
    id_metodo_pago INT NOT NULL REFERENCES metodos_de_pago(id_metodo_pago),
    CONSTRAINT ck_comprobante_fechaemision
    CHECK (
        (estado_comprobante = 'PENDIENTE' AND fecha_emision IS NULL) OR
        (estado_comprobante <> 'PENDIENTE' AND fecha_emision IS NOT NULL)
    )
);

CREATE TABLE boleta (
    id_boleta INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_cliente VARCHAR(100) NOT NULL,
    dni_cliente VARCHAR(20) NOT NULL,
    id_comprobante INT NOT NULL REFERENCES comprobante(id_comprobante)
);

CREATE TABLE factura (
    id_factura INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monto_base DECIMAL(10,2) NOT NULL,
    monto_impuesto DECIMAL(10,2) NOT NULL,
    razon_social_cliente VARCHAR(100) NOT NULL,
    ruc_cliente VARCHAR(20) NOT NULL,
    direccion_cliente VARCHAR(255),
    id_comprobante INT NOT NULL REFERENCES comprobante(id_comprobante)
);

CREATE TABLE detalle_pedido (
    id_detalle_pedido INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad INT NOT NULL,
    precio_unitario_venta DECIMAL(10,2) NOT NULL,
    subtotal DECIMAL(10,2) NOT NULL,
    id_pedido INT NOT NULL REFERENCES pedido(id_pedido),
    id_producto INT NOT NULL REFERENCES producto(id_producto)
);

CREATE TABLE devolucion (
    id_devolucion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_solicitud TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    estado_devolucion VARCHAR(50) NOT NULL,
    razon_devolucion TEXT NOT NULL,
    id_pedido INT NOT NULL REFERENCES pedido(id_pedido),
    id_usuario INT NOT NULL REFERENCES usuario(id_usuario)
);

CREATE TABLE detalle_devolucion (
    id_detalle_devolucion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad_devuelta INT NOT NULL,
    condicion_producto VARCHAR(50) NOT NULL,
    precio_unitario_devolucion DECIMAL(10,2) NOT NULL,
    id_devolucion INT NOT NULL REFERENCES devolucion(id_devolucion),
    id_detalle_pedido INT NOT NULL REFERENCES detalle_pedido(id_detalle_pedido)
);

CREATE TABLE reclamo (
    id_reclamo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_reclamo VARCHAR(100) NOT NULL,
    descripcion_problema TEXT NOT NULL,
    estado_reclamo VARCHAR(50) NOT NULL,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    id_usuario INT NOT NULL REFERENCES usuario(id_usuario)
);

CREATE TABLE historial (
    id_historial INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion TEXT NOT NULL,
    accion VARCHAR(100) NOT NULL,
    fecha_accion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    id_reclamo INT REFERENCES reclamo(id_reclamo),
    id_pedido INT REFERENCES pedido(id_pedido),
    id_usuario INT NOT NULL REFERENCES usuario(id_usuario)
);

CREATE TABLE carrito (
    id_carrito  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario  INT NOT NULL REFERENCES usuario(id_usuario),
    id_producto INT NOT NULL REFERENCES producto(id_producto),
    cantidad    INT NOT NULL CHECK (cantidad > 0),
    CONSTRAINT uq_carrito UNIQUE (id_usuario, id_producto)
);

-- ====================
-- 2. ÍNDICES DELIVERY
-- ====================

CREATE INDEX idx_envio_motorizado_estado ON envio (id_motorizado, estado_envio, fecha_asignacion);
CREATE INDEX idx_delivery_event_pedido ON delivery_event (id_pedido, created_at DESC);
CREATE INDEX idx_entrega_evidencia_pedido ON entrega_evidencia (id_pedido, created_at DESC);

-- ====================
-- 3. DATOS CORE
-- ====================

INSERT INTO metodos_de_pago (tipo_metodo, detalles) VALUES
('Mercado Pago', 'Pago online con Mercado Pago'),
('Contraentrega', 'Pago en efectivo al recibir');

INSERT INTO categoria (nombre_categoria) VALUES
('Abarrotes'),
('Bebidas'),
('Lácteos'),
('Frutas y Verduras'),
('Carnes'),
('Limpieza'),
('Panadería'),
('Congelados'),
('Snacks'),
('Cuidado Personal');

INSERT INTO marca (nombre_marca) VALUES
('Gloria'),
('Nestlé'),
('Coca-Cola'),
('Alicorp'),
('San Fernando'),
('Genérico');

INSERT INTO proveedor (nombre_proveedor, telefono, email, direccion) VALUES
('Distribuidora Alfa', '987333331', 'alfa@dist.com', 'Av. Argentina 123'),
('Mayorista Beta', '987333332', 'beta@mayorista.com', 'Av. Brasil 456');

INSERT INTO almacen (nombre_almacen, direccion, telefono, responsable) VALUES
('Almacén Central', 'Av. Industrial 123', '987222221', 'Luis Ramírez');

INSERT INTO delivery (nombre_empresa, telefono, email) VALUES
('Delivery Express', '987123456', 'express@delivery.com');

-- ====================
-- 4. USUARIOS DEMO
-- ====================

-- Password: 123 (para todos)
INSERT INTO usuario (nombre, apellido, email, contrasena, telefono, direccion_principal, rol, email_verificado) VALUES
('Cliente', 'Demo', 'cli@email.com', '$2a$10$tKJ56pQTAAvrb8Uerajsyuq5h30XvGp6NBaqwRGwZpF/ZkPsjUMPS', '987654321', 'Av. Lima 123', 'CLIENTE', true),
('Empleado', 'Demo', 'emp@email.com', '$2a$10$tKJ56pQTAAvrb8Uerajsyuq5h30XvGp6NBaqwRGwZpF/ZkPsjUMPS', '987654322', 'Av. Arequipa 456', 'EMPLEADO', true),
('Admin', 'Demo', 'admin@email.com', '$2a$10$tKJ56pQTAAvrb8Uerajsyuq5h30XvGp6NBaqwRGwZpF/ZkPsjUMPS', '987654323', 'Jr. Cusco 789', 'ADMINISTRADOR', true),
('Repartidor', 'Demo', 'repartidor@email.com', '$2a$10$tKJ56pQTAAvrb8Uerajsyuq5h30XvGp6NBaqwRGwZpF/ZkPsjUMPS', '987654331', 'Av. Delivery 100', 'REPARTIDOR', true);

-- Motorizado vinculado con usuario repartidor
INSERT INTO motorizado (nombre, apellido, telefono, licencia, id_delivery, id_usuario) VALUES
('Repartidor', 'Demo', '987111111', 'LIC001', 1, (SELECT id_usuario FROM usuario WHERE email = 'repartidor@email.com'));

-- ====================
-- 5. PRODUCTOS DEMO
-- ====================

INSERT INTO producto (nombre_producto, descripcion, precio, imagen, id_categoria, id_marca) VALUES
('Leche Gloria 1L', 'Leche entera 1L', 4.50, '/api/uploads/images/leche-gloria-1l.webp', 3, 1),
('Arroz Costeño 5kg', 'Arroz extra 5kg', 18.90, '/api/uploads/images/arroz-costeno-5kg.webp', 1, 4),
('Coca-Cola 3L', 'Gaseosa 3L', 10.50, '/api/uploads/images/coca-cola-3l.webp', 2, 3);

INSERT INTO inventario (cantidad_disponible, id_producto, id_almacen) VALUES
(100, 1, 1),
(150, 2, 1),
(200, 3, 1);

-- ====================
-- FIN
-- ====================

SELECT 'Inicialización completa: esquema + delivery v2 + datos demo' AS resultado;
