-- Migration: payments Mercado Pago structures required by runtime
-- Date: 2026-03-15
-- Source: apps/api/db/init/07_payments_mercadopago.sql

INSERT INTO metodos_de_pago (tipo_metodo, detalles)
SELECT 'Mercado Pago', 'Checkout Pro (redirect)'
WHERE NOT EXISTS (SELECT 1 FROM metodos_de_pago WHERE tipo_metodo = 'Mercado Pago');

CREATE TABLE IF NOT EXISTS payment_intent (
  id_payment_intent INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider VARCHAR(50) NOT NULL,
  id_pedido INT NOT NULL REFERENCES pedido(id_pedido),
  payment_method_id INT NOT NULL REFERENCES metodos_de_pago(id_metodo_pago),
  provider_preference_id VARCHAR(120) NULL,
  provider_init_point VARCHAR(2048) NULL,
  receipt_type VARCHAR(20) NOT NULL,
  receipt_data TEXT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'CREATED',
  provider_payment_id VARCHAR(120) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  confirmed_at TIMESTAMPTZ NULL,
  CONSTRAINT uq_paymentintent UNIQUE (provider, id_pedido)
);

CREATE TABLE IF NOT EXISTS payment_webhook_event (
  id_payment_webhook_event INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider VARCHAR(50) NOT NULL,
  event_id VARCHAR(200) NOT NULL,
  payment_id VARCHAR(120) NULL,
  raw_body TEXT NULL,
  received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  processed_at TIMESTAMPTZ NULL,
  CONSTRAINT uq_paymentwebhookevent UNIQUE (provider, event_id)
);
