-- Migration: delivery v2
-- Date: 2026-03-03
-- Source: apps/api/db/init/08_delivery_v2.sql

-- 1) Permitir rol REPARTIDOR en instalaciones existentes
ALTER TABLE usuario DROP CONSTRAINT IF EXISTS usuario_rol_check;
ALTER TABLE usuario
  ADD CONSTRAINT usuario_rol_check
  CHECK (rol IN ('CLIENTE', 'ADMINISTRADOR', 'EMPLEADO', 'REPARTIDOR'));

-- 2) Vincular motorizado con usuario del sistema
ALTER TABLE motorizado
  ADD COLUMN IF NOT EXISTS id_usuario INT NULL UNIQUE REFERENCES usuario(id_usuario);

-- 3) Extender tabla envio para operación de última milla
ALTER TABLE envio ADD COLUMN IF NOT EXISTS id_motorizado INT NULL REFERENCES motorizado(id_motorizado);
ALTER TABLE envio ADD COLUMN IF NOT EXISTS asignado_por INT NULL REFERENCES usuario(id_usuario);
ALTER TABLE envio ADD COLUMN IF NOT EXISTS fecha_asignacion TIMESTAMPTZ NULL;
ALTER TABLE envio ADD COLUMN IF NOT EXISTS fecha_inicio_ruta TIMESTAMPTZ NULL;
ALTER TABLE envio ADD COLUMN IF NOT EXISTS fecha_entrega TIMESTAMPTZ NULL;
ALTER TABLE envio ADD COLUMN IF NOT EXISTS motivo_no_entrega TEXT NULL;

-- 4) Eventos operativos de delivery (bitácora append-only)
CREATE TABLE IF NOT EXISTS delivery_event (
  id_delivery_event INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_envio INT NOT NULL REFERENCES envio(id_envio),
  id_pedido INT NOT NULL REFERENCES pedido(id_pedido),
  tipo_evento VARCHAR(50) NOT NULL,
  detalle TEXT NULL,
  payload_json TEXT NULL,
  id_usuario INT NULL REFERENCES usuario(id_usuario),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5) Evidencia de entrega
CREATE TABLE IF NOT EXISTS entrega_evidencia (
  id_entrega_evidencia INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_envio INT NOT NULL REFERENCES envio(id_envio),
  id_pedido INT NOT NULL REFERENCES pedido(id_pedido),
  nombre_receptor VARCHAR(120) NOT NULL,
  dni_receptor VARCHAR(20) NULL,
  observacion TEXT NULL,
  foto_url VARCHAR(2048) NULL,
  lat DECIMAL(10,7) NULL,
  lng DECIMAL(10,7) NULL,
  id_usuario INT NULL REFERENCES usuario(id_usuario),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_envio_motorizado_estado ON envio (id_motorizado, estado_envio, fecha_asignacion);
CREATE INDEX IF NOT EXISTS idx_delivery_event_pedido ON delivery_event (id_pedido, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_entrega_evidencia_pedido ON entrega_evidencia (id_pedido, created_at DESC);
