-- PostgreSQL schema

DROP TABLE IF EXISTS payment_webhook_event CASCADE;
DROP TABLE IF EXISTS payment_intent CASCADE;
DROP TABLE IF EXISTS historial CASCADE;
DROP TABLE IF EXISTS pedido_inventario_mov CASCADE;
DROP TABLE IF EXISTS reserva_stock_item CASCADE;
DROP TABLE IF EXISTS reserva_stock CASCADE;
DROP TABLE IF EXISTS detalle_pedido CASCADE;
DROP TABLE IF EXISTS boleta CASCADE;
DROP TABLE IF EXISTS factura CASCADE;
DROP TABLE IF EXISTS comprobante CASCADE;
DROP TABLE IF EXISTS envio CASCADE;
DROP TABLE IF EXISTS pedido CASCADE;
DROP TABLE IF EXISTS salida_inventario CASCADE;
DROP TABLE IF EXISTS entrada_inventario CASCADE;
DROP TABLE IF EXISTS inventario CASCADE;
DROP TABLE IF EXISTS motorizado CASCADE;
DROP TABLE IF EXISTS delivery CASCADE;
DROP TABLE IF EXISTS almacen CASCADE;
DROP TABLE IF EXISTS carrito CASCADE;
DROP TABLE IF EXISTS producto CASCADE;
DROP TABLE IF EXISTS marca CASCADE;
DROP TABLE IF EXISTS categoria CASCADE;
DROP TABLE IF EXISTS metodos_de_pago CASCADE;
DROP TABLE IF EXISTS password_reset_token CASCADE;
DROP TABLE IF EXISTS email_verification_token CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;

CREATE TABLE usuario (
    id_usuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    contrasena VARCHAR(255) NOT NULL,
    fecha_registro TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    telefono VARCHAR(20),
    direccion_principal VARCHAR(255),
    rol VARCHAR(15) NOT NULL DEFAULT 'CLIENTE' CHECK (rol IN ('CLIENTE', 'ADMINISTRADOR', 'EMPLEADO', 'REPARTIDOR')),
    email_verificado BOOLEAN NOT NULL DEFAULT FALSE,
    email_verificado_en TIMESTAMPTZ NULL
);

CREATE TABLE email_verification_token (
    id_email_verification_token INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INT NOT NULL REFERENCES usuario(id_usuario),
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    used_at TIMESTAMPTZ NULL,
    CONSTRAINT uq_emailverificationtoken UNIQUE (token_hash)
);

CREATE TABLE password_reset_token (
    id_password_reset_token INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INT NOT NULL REFERENCES usuario(id_usuario),
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    used_at TIMESTAMPTZ NULL,
    CONSTRAINT uq_passwordresettoken UNIQUE (token_hash)
);

CREATE TABLE metodos_de_pago (
    id_metodo_pago INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_metodo VARCHAR(50) NOT NULL,
    detalles VARCHAR(255)
);

CREATE TABLE categoria (
    id_categoria INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_categoria VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE marca (
    id_marca INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_marca VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE almacen (
    id_almacen INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_almacen VARCHAR(100) NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    responsable VARCHAR(100) NOT NULL
);

CREATE TABLE motorizado (
    id_motorizado INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    telefono VARCHAR(20) NOT NULL CHECK (LENGTH(TRIM(telefono)) > 0),
    licencia VARCHAR(50) NOT NULL CHECK (LENGTH(TRIM(licencia)) > 0),
    id_usuario INT NULL UNIQUE REFERENCES usuario(id_usuario)
);

CREATE TABLE producto (
    id_producto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_producto VARCHAR(100) NOT NULL,
    descripcion TEXT,
    precio DECIMAL(10,2) NOT NULL,
    imagen VARCHAR(255) NOT NULL DEFAULT '/assets/images/placeholder-product.png',
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    id_categoria INT NOT NULL REFERENCES categoria(id_categoria),
    id_marca INT NOT NULL REFERENCES marca(id_marca)
);

CREATE TABLE inventario (
    id_inventario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad_disponible INT NOT NULL,
    fecha_ultima_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    id_producto INT NOT NULL REFERENCES producto(id_producto),
    id_almacen INT NOT NULL REFERENCES almacen(id_almacen),
    CONSTRAINT uq_inventario_producto_almacen UNIQUE (id_producto, id_almacen)
);

CREATE TABLE entrada_inventario (
    id_entrada_inventario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad_recibida INT NOT NULL,
    fecha_entrada TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    motivo_entrada VARCHAR(255) NOT NULL,
    id_inventario INT NOT NULL REFERENCES inventario(id_inventario),
    id_usuario INT NULL REFERENCES usuario(id_usuario)
);

CREATE TABLE salida_inventario (
    id_salida_inventario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad_salida INT NOT NULL,
    fecha_salida TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    motivo_salida VARCHAR(255) NOT NULL,
    id_inventario INT NOT NULL REFERENCES inventario(id_inventario),
    id_usuario INT NULL REFERENCES usuario(id_usuario)
);

CREATE TABLE pedido (
    id_pedido INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    estado_pedido VARCHAR(50) NOT NULL
        CHECK (estado_pedido IN ('PENDIENTE_PAGO', 'PENDIENTE', 'PREPARADO', 'EN CAMINO', 'ENTREGADO', 'CANCELADO', 'REEMBOLSADO'))
        DEFAULT 'PENDIENTE_PAGO',
    total_pedido DECIMAL(10,2) NOT NULL,
    costo_envio DECIMAL(10,2),
    direccion_envio VARCHAR(255) NOT NULL,
    id_usuario INT NOT NULL REFERENCES usuario(id_usuario),
    id_metodo_pago INT NOT NULL REFERENCES metodos_de_pago(id_metodo_pago)
);

CREATE TABLE reserva_stock (
    id_reserva_stock INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INT NOT NULL REFERENCES pedido(id_pedido),
    id_usuario INT NOT NULL REFERENCES usuario(id_usuario),
    estado VARCHAR(20) NOT NULL CHECK (estado IN ('ACTIVA', 'CONSUMIDA', 'LIBERADA', 'EXPIRADA')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE reserva_stock_item (
    id_reserva_stock_item INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_reserva_stock INT NOT NULL REFERENCES reserva_stock(id_reserva_stock),
    id_producto INT NOT NULL REFERENCES producto(id_producto),
    cantidad INT NOT NULL CHECK (cantidad > 0),
    CONSTRAINT uq_reservastockitem UNIQUE (id_reserva_stock, id_producto)
);

CREATE TABLE pedido_inventario_mov (
    id_pedido_inventario_mov INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INT NOT NULL REFERENCES pedido(id_pedido),
    id_inventario INT NOT NULL REFERENCES inventario(id_inventario),
    tipo_mov VARCHAR(10) NOT NULL CHECK (tipo_mov IN ('SALIDA','ENTRADA')),
    cantidad INT NOT NULL CHECK (cantidad > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE envio (
    id_envio INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_rastreo VARCHAR(50) NOT NULL,
    transportista VARCHAR(100) NOT NULL,
    fecha_envio TIMESTAMPTZ,
    estado_envio VARCHAR(50) NOT NULL
        CHECK (estado_envio IN ('PENDIENTE', 'PENDIENTE_ASIGNACION', 'ASIGNADO', 'EN_RUTA', 'ENTREGADO', 'NO_ENTREGADO', 'REPROGRAMADO')),
    costo_envio DECIMAL(10,2) NOT NULL,
    id_pedido INT NOT NULL REFERENCES pedido(id_pedido)
);

CREATE TABLE comprobante (
    id_comprobante INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_comprobante VARCHAR(50) NOT NULL CHECK (tipo_comprobante IN ('BOLETA','FACTURA')),
    numero_comprobante VARCHAR(50) NOT NULL UNIQUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    monto_total DECIMAL(10,2) NOT NULL,
    estado_comprobante VARCHAR(50) NOT NULL CHECK (estado_comprobante IN ('PENDIENTE','PAGADO','ANULADO','OBSERVADO')),
    fecha_emision TIMESTAMPTZ NULL,
    ultima_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    id_pedido INT NOT NULL REFERENCES pedido(id_pedido),
    id_metodo_pago INT NOT NULL REFERENCES metodos_de_pago(id_metodo_pago),
    CONSTRAINT ck_comprobante_fechaemision
    CHECK (
        (estado_comprobante = 'PENDIENTE' AND fecha_emision IS NULL) OR
        (estado_comprobante <> 'PENDIENTE' AND fecha_emision IS NOT NULL)
    )
);

CREATE TABLE boleta (
    id_boleta INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_cliente VARCHAR(100) NOT NULL,
    dni_cliente VARCHAR(20) NOT NULL,
    id_comprobante INT NOT NULL REFERENCES comprobante(id_comprobante)
);

CREATE TABLE factura (
    id_factura INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monto_base DECIMAL(10,2) NOT NULL,
    monto_impuesto DECIMAL(10,2) NOT NULL,
    razon_social_cliente VARCHAR(100) NOT NULL,
    ruc_cliente VARCHAR(20) NOT NULL,
    direccion_cliente VARCHAR(255),
    id_comprobante INT NOT NULL REFERENCES comprobante(id_comprobante)
);

CREATE TABLE detalle_pedido (
    id_detalle_pedido INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad INT NOT NULL,
    precio_unitario_venta DECIMAL(10,2) NOT NULL,
    subtotal DECIMAL(10,2) NOT NULL,
    id_pedido INT NOT NULL REFERENCES pedido(id_pedido),
    id_producto INT NOT NULL REFERENCES producto(id_producto)
);

CREATE TABLE historial (
    id_historial INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion TEXT NOT NULL,
    accion VARCHAR(100) NOT NULL,
    fecha_accion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    modulo VARCHAR(50) NULL,
    entidad VARCHAR(50) NULL,
    referencia_id INT NULL,
    id_pedido INT REFERENCES pedido(id_pedido),
    id_usuario INT NOT NULL REFERENCES usuario(id_usuario)
);

CREATE TABLE carrito (
    id_carrito  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario  INT NOT NULL REFERENCES usuario(id_usuario),
    id_producto INT NOT NULL REFERENCES producto(id_producto),
    cantidad    INT NOT NULL CHECK (cantidad > 0),
    CONSTRAINT uq_carrito UNIQUE (id_usuario, id_producto)
);