-- PostgreSQL delivery v2 (idempotente)

-- 1) Permitir rol REPARTIDOR en instalaciones existentes
ALTER TABLE usuario DROP CONSTRAINT IF EXISTS usuario_rol_check;
ALTER TABLE usuario
  ADD CONSTRAINT usuario_rol_check
  CHECK (rol IN ('CLIENTE', 'ADMINISTRADOR', 'EMPLEADO', 'REPARTIDOR'));

-- 2) Vincular motorizado con usuario del sistema
ALTER TABLE motorizado
  ADD COLUMN IF NOT EXISTS id_usuario INT NULL UNIQUE REFERENCES usuario(id_usuario);

-- 3) Extender tabla envio para operación de última milla
ALTER TABLE envio ADD COLUMN IF NOT EXISTS id_motorizado INT NULL REFERENCES motorizado(id_motorizado);
ALTER TABLE envio ADD COLUMN IF NOT EXISTS asignado_por INT NULL REFERENCES usuario(id_usuario);
ALTER TABLE envio ADD COLUMN IF NOT EXISTS fecha_asignacion TIMESTAMPTZ NULL;
ALTER TABLE envio ADD COLUMN IF NOT EXISTS fecha_inicio_ruta TIMESTAMPTZ NULL;
ALTER TABLE envio ADD COLUMN IF NOT EXISTS fecha_entrega TIMESTAMPTZ NULL;
ALTER TABLE envio ADD COLUMN IF NOT EXISTS motivo_no_entrega TEXT NULL;

-- 4) Evidencia de entrega
CREATE TABLE IF NOT EXISTS entrega_evidencia (
  id_entrega_evidencia INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_envio INT NOT NULL REFERENCES envio(id_envio),
  id_pedido INT NOT NULL REFERENCES pedido(id_pedido),
  nombre_receptor VARCHAR(120) NOT NULL,
  dni_receptor VARCHAR(20) NULL,
  observacion TEXT NULL,
  id_usuario INT NULL REFERENCES usuario(id_usuario),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE entrega_evidencia DROP COLUMN IF EXISTS foto_url;
ALTER TABLE entrega_evidencia DROP COLUMN IF EXISTS lat;
ALTER TABLE entrega_evidencia DROP COLUMN IF EXISTS lng;

CREATE INDEX IF NOT EXISTS idx_envio_motorizado_estado ON envio (id_motorizado, estado_envio, fecha_asignacion);
CREATE INDEX IF NOT EXISTS idx_entrega_evidencia_pedido ON entrega_evidencia (id_pedido, created_at DESC);
